### ISSUE TITLE
Behaviour of getFrame

### ISSUE THREAD

**Issue by MathieuLeocmach** [MathieuLeocmach/read_lif#4]
In my original code, `getFrame` was returning frames in C order (ZYX), as written in the docstring.
However since the first commit on the present repository, axes are swapped before returning (XYZ). This change of behaviour raises various compatibility issues, including within the code (I fixed one in enumByFrame [recently](https://github.com/yangyushi/read_lif/commit/ce240f66fc5c9f42b25cdfec0ea7bd62506b8628#diff-f66a4f7aedaf7e0d3e34bf6f5ee7473f) ). Furthermore, the docstring has not been updated and is this misleading.

However, I want to keep the support for channels, introduced in @yangyushi version, since my old implementation was not taking channels into account.

I propose a new implementation of the function that reverts to the old behaviour but keeps support for channels. It is basically the new implementation without the axes swap and slightly better memory management.

**Comment by yangyushi** [comment]
Sure I just updated the readme document, will update the code pypi soon.

I will try to transfer the ownership of this repo to @MathieuLeocmach, since he is the original author.

@MathieuLeocmach, if you are also interested in maintaining the code on [pypi](https://pypi.org/project/read-lif/) I am happy to add you as the owner. In this case, I need your account name on pypi.
